### ISSUE TITLE
smooth()

### ISSUE THREAD

**Issue by shiffman** [shiffman/LearningProcessing#131]
https://github.com/processing/processing-docs/issues/250
https://github.com/processing/processing-docs/issues/251

**Comment by shiffman** [comment]
There's actually no mention of smooth() any more in the book, is that crazy?!  i guess i'll leave this open for a bit.

**Comment by ybakos** [comment]
I would remove it from any code listings and not worry about mentioning it... since since P2 smoothing is on by default. (right?)

**Comment by shiffman** [comment]
Great, yes, it's currently not anywhere in the book.  Just did a global find and it doesn't turn up.  Glad to have the moral support for this decision!
