### ISSUE TITLE
p105 universally unique variable names can mislead students

### ISSUE THREAD

**Issue by ybakos** [shiffman/LearningProcessing#150]
The last line "As a general rule, it’s better to never declare multiple variables with the same name in order to avoid this type of confusion." seems to be a decent rule of thumb to help prevent students from wandering into a situation where they unintentionally shadow a global.

However, I have found that the side effect of this thinking leads to students being "afraid" to use semantically meaningful names in local scopes, because they think that once they use a variable name anywhere, they _can not_ re-use that variable name.

Students have often tried to use unnecessarily different variable names in separate local scopes.

I might simply omit that last sentence, since a dialog about shadowing and lexical proximity doesn't seem appropriate at this point in the book / learning.

**Comment by shiffman** [comment]
Interesting!  Ok, taking it out.
