### ISSUE TITLE
7-5 Arguments could use some clarifying

### ISSUE THREAD

**Issue by ybakos** [shiffman/LearningProcessing#151]
Just a few pages ago I said “Let’s ignore ReturnType and Arguments.” I did this in order to ease into functions by sticking with the basics. However, functions possess greater powers than simply breaking a program into parts. One of the keys to unlocking these powers are the concepts of _arguments_ **and** _parameters_.

Arguments are values that are “passed” into a function. You can think of them as inputs that a function needs in order to do its job. A function that causes a creature to move a certain number of steps needs to know how many steps you want the creature to move. Instead of merely saying “Move,” you might say “Move 10 steps,” where 10 is the _argument_.

When you define such a "move" function, you are required to give each argument a name. That way, the function body can refer to the arguments it receives by the particular name that you specify. To illustrate, let’s rewrite drawBlackCircle() to include a parameter:

```
    void drawBlackCircle(int diameter) {
      fill(0);
      ellipse(50, 50, diameter, diameter);
    }
```
A parameter is simply a variable declaration inside the parentheses in the function definition. This variable is a local variable (Remember the discussion in Chapter 6?) to be used in that function (and only in that function). The **black** circle will be sized according to the value of `diameter`, which will  automatically be assigned the value of the _argument_ that you pass the function when you call `drawBlackCircle`. For example, when you call drawBlackCircle(100), the 100 is the argument. That 100 gets assigned to the diameter parameter, and the function body then uses diameter to draw the circle. When you call  drawBlackCircle(80), the 80 is the argument. That 80 gets assigned to the diameter parameter, and the function body then uses diameter to draw the circle.

**Comment by shiffman** [comment]
Thank you, these suggestions are amazing and super helpful.   I noticed you removed:

>When you display an ellipse in Processing, you are required to specify details about that ellipse. You can’t just say draw an ellipse, you have to say draw an ellipse at this location and with this size. These are the ellipse() function’s parameters as specified in the function definition. You encountered this concept in Chapter 1 when you learned to call functions for the first time.

I somewhat liked noting that this is how Processing works with all of its core functions.  Do you think I should work this back in or its unnecessary?

**Comment by ybakos** [comment]
Yeah, I know what you were getting at. If you want to keep it then I would show the function header for ellipse. My decision to eliminate it was because I felt the writing would have been redundant with what the drawBlackCircle example was already doing.

Now that I re-read those sentences, it makes sense after all, since you're trying to describe parameters at a high level.

**Comment by shiffman** [comment]
Thanks so much for this feedback!  Here's where it ended up (I'm going to remove the "bold" from the comments, looks weird to me.)

![screen shot 2015-06-17 at 11 27 29 am](https://cloud.githubusercontent.com/assets/191758/8204887/ef2bd71a-14e3-11e5-96e5-4293e6a42f5b.png)
