### ISSUE TITLE
15-1 Advising readers to always call loadImage within setup

### ISSUE THREAD

**Issue by ybakos** [shiffman/LearningProcessing#157]
One pitfall I've seen over and over again is when students call loadImage in "global scope," eg:
```
PImage foo = loadImage("foo.png");
void setup() {
}
```
The problem is that the path to the `data` dir isn't correctly set until right before `setup` is called. I don't believe there is anything cautioning the reader about this.

**Comment by shiffman** [comment]
The paragraph about avoiding draw for loading now reads

<p>I should also note that the process of loading the image from the hard drive into memory is a slow one, and you should make sure your sketches only have to do it once, in <code>setup()</code>. Loading images in <code>draw()</code> may result in slow performance, as well as “Out of Memory” errors.  You should also avoid calling <code>loadImage()</code> above <code>setup()</code> as Processing will not yet know the location of the "data" folder and will report an error.</p>
