### ISSUE TITLE
P315 More on filter > PShader

### ISSUE THREAD

**Issue by kasperkamperman** [shiffman/LearningProcessing#163]
Maybe good to mention that Processing also supports shaders in the "More on filter:" box. You can create your own filters or use the ones of others by using PShader. 

https://processing.org/reference/PShader.html
Tutorial: https://processing.org/tutorials/pshader/

https://github.com/SableRaf/Filters4Processing

**Comment by shiffman** [comment]
Adding:

<p>In addition, while beyond the scope of this book, Processing also supports <em>shaders</em> via the <code>PShader</code> class. Shaders are low-level programs written in a special language called GLSL (OpenGL Shading Language) and can be used for a variety of computer graphics effects, including image processing.  <code>PShader</code> is available for use with both the <code>P3D</code> and <code>P2D</code> renderers and you can learn more by reading the <a href="https://processing.org/tutorials/pshader/">processing.org <code>PShader</code> tutorial by Andres Colubri</a>.</p>.  

Would welcome any further feedback!
