### ISSUE TITLE
Can't find book's exercises solutions anywhere, anymore :(

### ISSUE THREAD

**Issue by AnonGreen** [shiffman/LearningProcessing#178]
Hi there, I am now studying the  1st edition of the book and I would really like to find somewhere online the results for the exercises included in it.

Where can I find them online? Is there still an url for the old website pages with exercises + other users comments?

Thank you very much!

A.

**Comment by shiffman** [comment]
I've got the old site up and running (somewhat) here:

http://learningprocessing.dreamhosters.com/
