### ISSUE TITLE
2.6 errors

### ISSUE THREAD

**Issue by shiffman** [shiffman/LearningProcessing#66]
this no longer applies

"<p>In this instance, there was only one error. If multiple errors occur, <em>Processing</em> will only alert you to the first one it finds (and presumably, once that error is corrected, the next error will be displayed at run time). This is somewhat of an unfortunate limitation, as it is often useful to have access to an entire list of errors when fixing a program. This is simply one of the trade-offs we get in a simplified environment such as <em>Processing.</em> Our life is made simpler by only having to look at one error at a time, nevertheless we do not have access to a complete list.</p>"

**Comment by hongmak** [comment]
I've encountered a problem. "JDWP to transports initialized, jvmtiError...". I've reinstalled jdk but it's still not working. Could you give me some advice?

**Comment by shiffman** [comment]
Please ask at http://forum.processing.org.  I would need more specifics, code + screenshot of error?

**Comment by hongmak** [comment]
[image: 内嵌图片 1]
I've tried the 1.5 and 2.2 version and I think the problem must lay on the
JVM. I researched on Google but no one can actually solve it.

2015-02-26 17:32 GMT+08:00 Daniel Shiffman <notifications@github.com>:
