### ISSUE TITLE
new string exercise

### ISSUE THREAD

**Issue by shiffman** [shiffman/LearningProcessing#75]
Add an exercise “Write a function called substr(String s, int startPos, int nChars)”. Of course, it's not a method, and you can't subclass String, but...

@jdeisenberg where are you suggesting this goes?

**Comment by jdeisenberg** [comment]
Right after the text where you introduce substring() and note how inconvenient it is to have parameters as (start, end).

**Comment by shiffman** [comment]
Here's what I've got at the moment.

---------------------
Write your own &ldquo;substring&rdquo; function that receives three arguments: a String, a starting position, and a total number of characters.  The function should return the corresponding substring starting at the position and with a length matching the number.  Here's some code to get you started.

```
void substring(String txt, int start, int num) {

  return __________________________________;  
}
```
